### ISSUE TITLE
SSL Support Status?

### ISSUE THREAD

**Issue by phipolis** [TingPing/transmission-remote-gnome#1]
Does transmission-remote-gnome work with ssl connections? I run transmission-daemon behind an nginx ssl proxy ([similar to this](https://gist.github.com/michaelkeevildown/072b2f94af6bfa1416ee44c7004aff43)) and am able to connect using transdroid or transmission-remote-gtk by checking SSL in the connection settings. However, transmission-remote-gnome emits the error `WARNING:root:Response was not successful: SOUP_STATUS_BAD_REQUEST (400)`

I'm not sure if this is related, but the only mention of 'SSL' I find in the code is the line `--env=SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt"` in `se.tingping.Trg.json`; however on my system (Fedora 25) this file does not exist, there is only `ca-bundle.crt` and `ca-bundle.trust.crt`. Creating a file at that path does not help.

**Comment by TingPing** [comment]
Not yet, shouldn't be much work just need a setup to test it.

**Comment by phipolis** [comment]
Fantastic! That allows me to connect! Thank you!! The only thing possibly amiss is the log message `WARNING:root:Response was not successful: SOUP_STATUS_CONFLICT (409)`. 

The 'Remote' tab in preferences is also empty, but I assume that isn't implemented yet.

**Comment by TingPing** [comment]
You should always get a single 409 on first connect but it should resolve itself.

> The 'Remote' tab in preferences is also empty, but I assume that isn't implemented yet.

Yea, on the TODO list...

**Comment by TingPing** [comment]
@phipolis BTW: https://github.com/TingPing/transmission-remote-gnome/commit/7be98a7cf806ae16fbee0ac8238ff82944fac2df
